Importação das bibliotecas:
- Pandas: para manipulação de dados através do alias "pd"
- Google Colab: para manipulação de arquivos no Google Drive

E execução do comando "%matplotlib inline" para que os gráficos sejam exibidos no notebook logo abaixo da célula de código que os gerou.

In [5]:
import pandas as pd
from google.colab import drive

%matplotlib inline

Carregamento do Drive para que o notebook possa acessar os arquivos do Google Drive e com o parâmetro "force_remount=True" para que o Drive seja montado a cada execução do notebook.

In [6]:
drive.mount('/content/drive', force_remount=True)

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

Leitura do arquivo "dataset.csv" através da função "read_csv" do Pandas e armazenamento do resultado na variável "df". Uso do parâmetro "sep" para informar qual o separador de colunas do arquivo e do parâmetro "encoding" para informar qual o tipo de codificação do arquivo.

In [35]:
csv_url = "https://github.com/viniciusgugelmin/data-science/blob/main/projects/base_de_despesas/data/dataset.csv?raw=true"

df = pd.read_csv(csv_url, sep=';', encoding='iso-8859-1')

Exibição das 5 primeiras linhas do DataFrame através da função "head" do Pandas para verificar se o arquivo foi carregado corretamente e ter uma ideia do que ele contém.

In [36]:
df.head()

,ANO_EMPENHO,DT_EMPENHO,CD_FONTE,DS_FONTE,CD_FUNCAO,DS_FUNCAO,CD_PROGRAMA,DS_PROGRAMA,CD_ACAO,DS_ACAO,...,VL_TOTAL,PROTOCOLOSUP,DT_TRANSACAO,NR_PARCELA,TRANSACAO,VL_LIQUIDADO,VL_DEVOLVIDO,VL_ANULADO,VL_PAGO,VL_CONSIGNADO
0,-----------,----------,--------,--------,---------,---------,-----------,-----------,-------,-------,...,--------,------------,------------,------------,------------,------------,------------,----------,-------,-------------
1,2022,2022-06-09,098,Recursos Próprios do Fundo Municipal de Apoio ...,08,ASSISTÊNCIA SOCIAL,0001,PROGRAMA VIVA CURITIBA QUE NÃO DORME,2011,DESENVOLVIMENTO E EXECUÇÃO DE AÇÕES DE ATENDIM...,...,"2115,0000",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2022,2022-06-09,098,Recursos Próprios do Fundo Municipal de Apoio ...,08,ASSISTÊNCIA SOCIAL,0001,PROGRAMA VIVA CURITIBA QUE NÃO DORME,2011,DESENVOLVIMENTO E EXECUÇÃO DE AÇÕES DE ATENDIM...,...,"804,0000",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2022,2022-06-23,024,Recursos Próprios do Fundo Municipal de Habita...,16,HABITAÇÃO,0002,PROGRAMA VIVA CURITIBA CIDADÃ,2066,"MANUTENÇÃO E EXECUÇÃO DOS SERVIÇOS TÉCNICOS, A...",...,NaN,01-122405/2022,2022-07-22 00:00:00.000,1,Anulado de Empenho,"0,00","0,00","532,44","0,00","0,00"
4,2022,2022-06-23,024,Recursos Próprios do Fundo Municipal de Habita...,16,HABITAÇÃO,0002,PROGRAMA VIVA CURITIBA CIDADÃ,2066,"MANUTENÇÃO E EXECUÇÃO DOS SERVIÇOS TÉCNICOS, A...",...,NaN,01-122405/2022,2022-07-14 00:00:00.000,1,Pagamento de Empenho,"0,00","0,00","0,00","1133,44","0,00"

Exclusão da coluna de índice 0 do DataFrame através da função "drop" do Pandas, pois ela é composta apenas por traços e não possui nenhum valor relevante além de separar as linhas do cabeçalho visualmente.

In [37]:
df = df.drop(0)
df

Reset do index do DataFrame através da função "reset_index" do Pandas para que o index seja redefinido a partir do 0 e utilização do parâmetro "drop=True" para que a coluna de índice antiga seja excluída.

In [41]:
df.reset_index(drop=True)

,ANO_EMPENHO,DT_EMPENHO,CD_FONTE,DS_FONTE,CD_FUNCAO,DS_FUNCAO,CD_PROGRAMA,DS_PROGRAMA,CD_ACAO,DS_ACAO,...,VL_TOTAL,PROTOCOLOSUP,DT_TRANSACAO,NR_PARCELA,TRANSACAO,VL_LIQUIDADO,VL_DEVOLVIDO,VL_ANULADO,VL_PAGO,VL_CONSIGNADO
0,2022,2022-06-09,098,Recursos Próprios do Fundo Municipal de Apoio ...,08,ASSISTÊNCIA SOCIAL,0001,PROGRAMA VIVA CURITIBA QUE NÃO DORME,2011,DESENVOLVIMENTO E EXECUÇÃO DE AÇÕES DE ATENDIM...,...,"2115,0000",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2022,2022-06-09,098,Recursos Próprios do Fundo Municipal de Apoio ...,08,ASSISTÊNCIA SOCIAL,0001,PROGRAMA VIVA CURITIBA QUE NÃO DORME,2011,DESENVOLVIMENTO E EXECUÇÃO DE AÇÕES DE ATENDIM...,...,"804,0000",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2022,2022-06-23,024,Recursos Próprios do Fundo Municipal de Habita...,16,HABITAÇÃO,0002,PROGRAMA VIVA CURITIBA CIDADÃ,2066,"MANUTENÇÃO E EXECUÇÃO DOS SERVIÇOS TÉCNICOS, A...",...,NaN,01-122405/2022,2022-07-22 00:00:00.000,1,Anulado de Empenho,"0,00","0,00","532,44","0,00","0,00"
3,2022,2022-06-23,024,Recursos Próprios do Fundo Municipal de Habita...,16,HABITAÇÃO,0002,PROGRAMA VIVA CURITIBA CIDADÃ,2066,"MANUTENÇÃO E EXECUÇÃO DOS SERVIÇOS TÉCNICOS, A...",...,NaN,01-122405/2022,2022-07-14 00:00:00.000,1,Pagamento de Empenho,"0,00","0,00","0,00","1133,44","0,00"
4,2022,2022-06-23,024,Recursos Próprios do Fundo Municipal de Habita...,16,HABITAÇÃO,0002,PROGRAMA VIVA CURITIBA CIDADÃ,2066,"MANUTENÇÃO E EXECUÇÃO DOS SERVIÇOS TÉCNICOS, A...",...,NaN,01-122405/2022,2022-07-13 00:00:00.000,1,Liquidação de Empenho,"1133,44","0,00","0,00","0,00","0,00"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
36081,2022,2022-08-31,114,Programa Dinheiro Direto na Escola - PDDE - Ed...,12,EDUCAÇÃO,2,PROGRAMA VIVA CURITIBA CIDADÃ,2038,TRANSFERÊNCIA DE RECURSOS ÀS ENTIDADES PRIVADA...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
36082,2022,2022-08-31,114,Programa Dinheiro Direto na Escola - PDDE - Ed...,12,EDUCAÇÃO,2,PROGRAMA VIVA CURITIBA CIDADÃ,2038,TRANSFERÊNCIA DE RECURSOS ÀS ENTIDADES PRIVADA...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
36083,2022,2022-08-31,114,Programa Dinheiro Direto na Escola - PDDE - Ed...,12,EDUCAÇÃO,2,PROGRAMA VIVA CURITIBA CIDADÃ,2038,TRANSFERÊNCIA DE RECURSOS ÀS ENTIDADES PRIVADA...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
36084,2022,2022-08-31,0,Recursos Ordinários (Livres),4,ADMINISTRAÇÃO,7,PROGRAMA VIVA CURITIBA TRANSPARENTE,2164,"PROMOÇÃO DA ASSISTÊNCIA GERAL AO SERVIDOR, CON...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
36085,2022,2022-08-31,103,5% Sobre Transferências Constitucionais FUNDEB,12,EDUCAÇÃO,2,PROGRAMA VIVA CURITIBA CIDADÃ,2026,MANUTENÇÃO DA ESTRUTURA FUNCIONAL SME,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN